# Generated by Django 3.2.7 on 2022-03-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandaPersonaNatural', '0006_alter_demandapersonanaturalmodel_fechademandapersonanatural'),
        ('demandaEmpresa', '0005_alter_demandaempresamodel_montototaldemandapersjuri'),
        ('conflictoDespidoSJC', '0002_auto_20220310_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictodespidosjcmodel',
            name='demandaEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demandaEmpresa.demandaempresamodel'),
        ),
        migrations.AlterField(
            model_name='conflictodespidosjcmodel',
            name='demandaPersonaNatural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demandaPersonaNatural.demandapersonanaturalmodel'),
        ),
    ]
