# Generated by Django 3.2.7 on 2022-03-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflictoDespidoSJC', '0003_auto_20220310_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictodespidosjcmodel',
            name='montoDinero_DSJC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conflictodespidosjcmodel',
            name='tipoContrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
