# Generated by Django 3.2.7 on 2022-03-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandaPersonaNatural', '0006_alter_demandapersonanaturalmodel_fechademandapersonanatural'),
        ('demandaEmpresa', '0005_alter_demandaempresamodel_montototaldemandapersjuri'),
        ('contratoLaboral', '0003_contratolaboralmodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictoPrimasModel',
            fields=[
                ('fechaUltimaPrimaPagada', models.DateTimeField(blank=True, null=True)),
                ('fechaFinalNoPagoPrima', models.DateTimeField(blank=True, null=True)),
                ('montoDinero_Prima', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratoLaboral.contratolaboralmodel')),
                ('demandaEmpresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demandaEmpresa.demandaempresamodel')),
                ('demandaPersonaNatural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demandaPersonaNatural.demandapersonanaturalmodel')),
            ],
        ),
    ]
