# Generated by Django 3.2.7 on 2022-03-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratoLaboral', '0003_contratolaboralmodel_is_active'),
        ('demandaEmpresa', '0005_alter_demandaempresamodel_montototaldemandapersjuri'),
        ('demandaPersonaNatural', '0006_alter_demandapersonanaturalmodel_fechademandapersonanatural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictoLiquidacionModel',
            fields=[
                ('fechaInicioLiquidacion', models.DateTimeField(blank=True, null=True)),
                ('fechaFinalLiquidacion', models.DateTimeField(blank=True, null=True)),
                ('diasDeVacaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('montoDinero_Prima', models.CharField(blank=True, max_length=255, null=True)),
                ('montoDinero_Vacaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratoLaboral.contratolaboralmodel')),
                ('demandaEmpresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demandaEmpresa.demandaempresamodel')),
                ('demandaPersonaNatural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demandaPersonaNatural.demandapersonanaturalmodel')),
            ],
        ),
    ]
