# Generated by Django 3.2.7 on 2022-03-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflictoInteresesCesantias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictointeresescesantiasmodel',
            name='montoDinero_InteresesCesantias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
