# Generated by Django 3.2.7 on 2021-10-06 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_alter_personmodel_lugarresidenciapersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaNaturalModel',
            fields=[
                ('personmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='persona.personmodel')),
                ('idPersonaNatural', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('persona.personmodel',),
        ),
    ]
