# Generated by Django 3.2.7 on 2021-10-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona_natural', '0002_auto_20211006_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personanaturalmodel',
            old_name='persona',
            new_name='person',
        ),
    ]
