# Generated by Django 3.2.7 on 2022-03-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandaEmpresa', '0005_alter_demandaempresamodel_montototaldemandapersjuri'),
        ('demandaPersonaNatural', '0006_alter_demandapersonanaturalmodel_fechademandapersonanatural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictoContactaAbogadoModel',
            fields=[
                ('conflictoARL', models.BooleanField(blank=True, default=False, null=True)),
                ('conflictoPensiones', models.BooleanField(blank=True, default=False, null=True)),
                ('conflictoHorasExtras', models.BooleanField(blank=True, default=False, null=True)),
                ('conflictoDominicalesFestivos', models.BooleanField(blank=True, default=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('demandaEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandaEmpresa.demandaempresamodel')),
                ('demandaPersonaNatural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandaPersonaNatural.demandapersonanaturalmodel')),
            ],
        ),
    ]
