# Generated by Django 3.2.7 on 2021-10-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona_natural', '0003_rename_persona_personanaturalmodel_person'),
        ('user_profile', '0001_initial'),
        ('contratoLaboral', '0003_contratolaboralmodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandapersonanatural',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('fechademandapersonanatural', models.DateField(db_column='fechaDemandaPersonaNatural')),
                ('fechapropuestaradicaciondemandapersonan', models.DateField(blank=True, db_column='fechaPropuestaRadicacionDemandaPersonaN', null=True)),
                ('fecharrealradicaciondemandapersonan', models.DateField(blank=True, db_column='fecharRealRadicacionDemandaPersonaN', null=True)),
                ('fechapropuestaradicacionderechopetipersonan', models.DateField(blank=True, db_column='fechaPropuestaRadicacionDerechoPetiPersonaN', null=True)),
                ('fecharrealradicacionderechopetipersonan', models.DateField(blank=True, db_column='fecharRealRadicacionDerechoPetiPersonaN', null=True)),
                ('informedesicionfinaldemandapersonan', models.TextField(blank=True, db_column='informeDesicionFinalDemandaPersonaN', null=True)),
                ('respuestafinaldemandaersonan', models.TextField(blank=True, db_column='respuestaFinalDemandaersonaN', null=True)),
                ('montototaldemandapersnat', models.FloatField(blank=True, db_column='montoTotalDemandaPersNat', null=True)),
                ('superaminimacuantiapersnat', models.TextField(blank=True, db_column='superaMinimaCuantiaPersNat', null=True)),
                ('contrato', models.ForeignKey(db_column='contrato', on_delete=django.db.models.deletion.DO_NOTHING, to='contratoLaboral.contratolaboralmodel')),
                ('personanatural', models.ForeignKey(db_column='personaNatural', on_delete=django.db.models.deletion.DO_NOTHING, to='persona_natural.personanaturalmodel')),
                ('ubicacion', models.ForeignKey(db_column='ubicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.municipios')),
            ],
        ),
    ]
