# Generated by Django 3.2.7 on 2021-10-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('contratoLaboral', '0003_contratolaboralmodel_is_active'),
        ('persona_natural', '0003_rename_persona_personanaturalmodel_person'),
        ('demandaPersonaNatural', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demandapersonanatural',
            new_name='DemandaPersonaNaturalModel',
        ),
    ]
