# Generated by Django 3.2.7 on 2021-10-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratoLaboral', '0003_contratolaboralmodel_is_active'),
        ('user_profile', '0001_initial'),
        ('persona_natural', '0003_rename_persona_personanaturalmodel_person'),
        ('demandaPersonaNatural', '0002_rename_demandapersonanatural_demandapersonanaturalmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandapersonanaturalmodel',
            name='contrato',
            field=models.ForeignKey(blank=True, db_column='contrato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contratoLaboral.contratolaboralmodel'),
        ),
        migrations.AlterField(
            model_name='demandapersonanaturalmodel',
            name='fechademandapersonanatural',
            field=models.DateField(blank=True, db_column='fechaDemandaPersonaNatural', null=True),
        ),
        migrations.AlterField(
            model_name='demandapersonanaturalmodel',
            name='personanatural',
            field=models.ForeignKey(blank=True, db_column='personaNatural', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='persona_natural.personanaturalmodel'),
        ),
        migrations.AlterField(
            model_name='demandapersonanaturalmodel',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_column='ubicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.municipios'),
        ),
    ]
