# Generated by Django 3.2.7 on 2021-10-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandaPersonaNatural', '0003_auto_20211016_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandapersonanaturalmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
