# Generated by Django 3.2.7 on 2021-10-16 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_personmodel_lugarresidenciapersona'),
        ('demandaPersonaNatural', '0004_demandapersonanaturalmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandapersonanaturalmodel',
            name='demandante',
            field=models.ForeignKey(blank=True, db_column='demandante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='persona.personmodel'),
        ),
    ]
