# Generated by Django 3.2.7 on 2022-03-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_personmodel_lugarresidenciapersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='idmodel',
            name='country',
            field=models.CharField(blank=True, db_column='country', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='idmodel',
            name='haveColombianId',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', max_length=70, null=True),
        ),
    ]
