# Generated by Django 3.2.7 on 2022-03-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratoLaboral', '0003_contratolaboralmodel_is_active'),
        ('conflictoPagoSalario', '0002_rename_conflictopagosalario_conflictopagosalariomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictopagosalariomodel',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratoLaboral.contratolaboralmodel'),
        ),
    ]
