# Generated by Django 3.2.7 on 2021-09-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('persona', '0002_alter_personmodel_lugarresidenciapersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultoriojuridico',
            fields=[
                ('idconsultoriojuridico', models.AutoField(db_column='IdconsultorioJuridico', primary_key=True, serialize=False)),
                ('tipoconsultoriojuridico', models.CharField(blank=True, db_column='tipoConsultorioJuridico', max_length=100, null=True)),
                ('nombreconsultoriojuridico', models.CharField(db_column='nombreConsultorioJuridico', max_length=300)),
                ('telefonoconsultoriojuridico', models.IntegerField(db_column='telefonoConsultorioJuridico')),
                ('emailconsultoriojuridico', models.CharField(blank=True, db_column='emailConsultorioJuridico', max_length=100, null=True)),
                ('direccionconsultoriojuridico', models.CharField(blank=True, db_column='direccionConsultorioJuridico', max_length=200, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.municipios')),
                ('personaencargada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.personmodel')),
            ],
        ),
    ]
