# Generated by Django 3.2.7 on 2021-09-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioJuridico', '0002_alter_consultoriojuridico_emailconsultoriojuridico'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultoriojuridico',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
