# Generated by Django 3.2.7 on 2021-09-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='departamento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.departamentos'),
        ),
    ]
