# Generated by Django 2.2 on 2021-09-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apellidospersona',
            field=models.CharField(blank=True, db_column='apellidosPersona', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='direccionpersona',
            field=models.CharField(blank=True, db_column='direccionPersona', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fechanacimientopersona',
            field=models.DateField(blank=True, db_column='fechaNacimientoPersona', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='generopersona',
            field=models.CharField(blank=True, db_column='generoPersona', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lugarexpedicioncedulapersona',
            field=models.IntegerField(blank=True, db_column='lugarExpedicionCedulaPersona', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombrespersona',
            field=models.CharField(blank=True, db_column='nombresPersona', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='numerodocumentopersona',
            field=models.IntegerField(blank=True, db_column='numeroDocumentoPersona', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipodocumentopersona',
            field=models.CharField(blank=True, db_column='tipoDocumentoPersona', max_length=70, null=True),
        ),
    ]
