# Generated by Django 2.2 on 2021-09-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210921_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apellidospersona',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='direccionpersona',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fechanacimientopersona',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='generopersona',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lugarexpedicioncedulapersona',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nombrespersona',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='numerodocumentopersona',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tipodocumentopersona',
        ),
    ]
