# Generated by Django 3.2.7 on 2021-10-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0003_empresamodel_ubicacion'),
        ('persona_natural', '0003_rename_persona_personanaturalmodel_person'),
        ('persona', '0002_alter_personmodel_lugarresidenciapersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoLaboral',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('tipocontrato', models.CharField(db_column='tipoContrato', max_length=100)),
                ('fechainiciocontrato', models.DateField(db_column='fechaInicioContrato')),
                ('fechafinalcontrato', models.DateField(blank=True, db_column='fechaFinalContrato', null=True)),
                ('ultimosalario', models.IntegerField(db_column='ultimoSalario')),
                ('descripcionfunciones', models.TextField(db_column='descripcionFunciones')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresamodel')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.personmodel')),
                ('personaNatural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona_natural.personanaturalmodel')),
            ],
        ),
    ]
