# Generated by Django 3.2.7 on 2021-10-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratoLaboral', '0002_rename_contratolaboral_contratolaboralmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolaboralmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
