# Generated by Django 3.2.7 on 2021-10-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
