# Generated by Django 3.2.7 on 2021-10-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('empresa', '0002_empresamodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.municipios'),
        ),
    ]
