# Generated by Django 3.2.7 on 2022-03-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0003_empresamodel_ubicacion'),
        ('user_profile', '0001_initial'),
        ('contratoLaboral', '0003_contratolaboralmodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaEmpresaModel',
            fields=[
                ('fechaDemandaEmpresa', models.DateTimeField(blank=True, null=True)),
                ('tipoDocumentoPersona', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('numeroDocumentoPersona', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fechaPropuestaRadicacionDemandaEmpresa', models.DateTimeField(blank=True, null=True)),
                ('fecharRealRadicacionDemandaEmpresa', models.DateTimeField(blank=True, null=True)),
                ('fechaPropuestaRadicacionDerechoPetiEmpresa', models.DateTimeField(blank=True, null=True)),
                ('fecharRealRadicacionDerechoPetiEmpresa', models.DateTimeField(blank=True, null=True)),
                ('informeDesicionFinalDemandaEmpresa', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('respuestaFinalDemandaEmpresa', models.BooleanField(default=True)),
                ('montoTotalDemandaPersJuri', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('superaMinimaCuantiaPersJuri', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('NItEmpresa', models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresamodel')),
                ('codigoCiudad', models.ForeignKey(blank=True, db_column='ubicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.municipios')),
                ('idContrato', models.ForeignKey(blank=True, db_column='contrato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contratoLaboral.contratolaboralmodel')),
            ],
        ),
    ]
