# Generated by Django 3.2.7 on 2022-03-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandaEmpresa', '0003_alter_demandaempresamodel_numerodocumentopersona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandaempresamodel',
            name='informeDesicionFinalDemandaEmpresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
