# Generated by Django 3.2.7 on 2021-09-23 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipodocumentopersona', models.CharField(blank=True, db_column='tipoDocumentoPersona', max_length=70, null=True)),
                ('numerodocumentopersona', models.IntegerField(blank=True, db_column='numeroDocumentoPersona', null=True)),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrespersona', models.CharField(blank=True, db_column='nombresPersona', max_length=70, null=True)),
                ('apellidospersona', models.CharField(blank=True, db_column='apellidosPersona', max_length=70, null=True)),
                ('fechanacimientopersona', models.DateField(blank=True, db_column='fechaNacimientoPersona', null=True)),
                ('direccionpersona', models.CharField(blank=True, db_column='direccionPersona', max_length=70, null=True)),
                ('generopersona', models.CharField(blank=True, db_column='generoPersona', max_length=70, null=True)),
                ('lugarresidenciapersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.municipios')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
